use std::fs;

/// Convert SRT entries to ASS subtitle format for ffmpeg burn-in.
/// Matches the behavior of the Python ass_from_srt.py script.
pub fn srt_to_ass(
    entries: &[(f64, f64, String)],
    output_path: &str,
    style_name: &str,
) -> Result<(), std::io::Error> {
    let header = r#"[Script Info]
; Script generated by openscript-rs
ScriptType: v4.00+
WrapStyle: 0
PlayResX: 1080
PlayResY: 1920

[V4+ Styles]
Format: Name,Fontname,Fontsize,PrimaryColour,SecondaryColour,OutlineColour,BackColour,Bold,Italic,Underline,StrikeOut,ScaleX,ScaleY,Spacing,Angle,BorderStyle,Outline,Shadow,Alignment,MarginL,MarginR,MarginV,Encoding
Style: #STYLE#,Bebas Neue,84,&H00FFFFFF,&H000000FF,&H00000000,&H80000000,-1,0,0,0,100,100,0,0,1,3,5,5,108,108,0,1
"#;
    let header = header.replace("#STYLE#", style_name);

    let mut body = String::from(
        "[Events]\nFormat: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text\n",
    );

    for (start, end, text) in entries {
        let start_str = format_timestamp_ass(*start);
        let end_str = format_timestamp_ass(*end);
        let escaped = text
            .replace('\\', "\\\\")
            .replace('{', "\\{")
            .replace('}', "\\}");
        body.push_str(&format!(
            "Dialogue: 0,{}, {}, {},,0,0,0,,{}\n",
            start_str, end_str, style_name, escaped
        ));
    }

    fs::write(output_path, format!("{}\n{}", header, body))
}

fn format_timestamp_ass(seconds: f64) -> String {
    let secs = if seconds < 0.0 { 0.0 } else { seconds };
    let cs = ((secs % 1.0) * 100.0).round() as u32;
    let s_int = secs as u64;
    let hh = s_int / 3600;
    let mm = (s_int % 3600) / 60;
    let ss = s_int % 60;
    format!("{:01}:{:02}:{:02}.{:02}", hh, mm, ss, cs)
}

fn escape_ass_text(text: &str) -> String {
    text.replace('\\', "\\\\")
        .replace('{', "\\{")
        .replace('}', "\\}")
}

/// Generate kinetic (viral-style) ASS subtitles with word-by-word display.
/// Shows 2-3 words at a time, all in bold highlighted style, creating rapid
/// word-by-word pop-up effect seen in viral reels. Center-aligned with Bebas Neue font.
///
/// Each input entry represents a full caption, which is split into word groups.
/// For each word group, a separate ASS Dialogue line is created with timing split evenly.
pub fn generate_kinetic_captions(
    entries: &[(f64, f64, String)],
    output_path: &str,
    style_name: &str,
    highlight_color: &str,
) -> Result<(), std::io::Error> {
    let header = format!(
        r#"[Script Info]
; Script generated by openscript-rs (kinetic captions)
ScriptType: v4.00+
WrapStyle: 0
PlayResX: 1080
PlayResY: 1920

[V4+ Styles]
Format: Name,Fontname,Fontsize,PrimaryColour,SecondaryColour,OutlineColour,BackColour,Bold,Italic,Underline,StrikeOut,ScaleX,ScaleY,Spacing,Angle,BorderStyle,Outline,Shadow,Alignment,MarginL,MarginR,MarginV,Encoding
Style: KineticBold,Bebas Neue,88,&H00FFFFFF,&H000000FF,&H00000000,&H80000000,1,0,0,0,100,100,0,0,1,4,5,5,108,108,0,1
Style: KineticDim,Bebas Neue,72,&H00808080,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,2,5,5,108,108,0,1
Style: {},Bebas Neue,88,{},&H000000FF,&H00000000,&H80000000,1,0,0,0,100,100,0,0,1,4,5,5,108,108,0,1
"#,
        style_name, highlight_color
    );

    let mut body = String::from(
        "[Events]\nFormat: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text\n",
    );

    for (start, end, text) in entries {
        let words: Vec<&str> = text.split_whitespace().collect();
        if words.is_empty() {
            continue;
        }

        let chunks = group_words(&words);
        let duration = end - start;
        let chunk_duration = if chunks.is_empty() {
            0.0
        } else {
            duration / chunks.len() as f64
        };

        for (i, chunk) in chunks.iter().enumerate() {
            let chunk_start = start + (i as f64 * chunk_duration);
            let chunk_end = chunk_start + chunk_duration;
            let start_str = format_timestamp_ass(chunk_start);
            let end_str = format_timestamp_ass(chunk_end);
            let escaped = escape_ass_text(chunk);

            body.push_str(&format!(
                "Dialogue: 0,{},{},{},,108,108,0,,{}\n",
                start_str, end_str, style_name, escaped
            ));
        }
    }

    fs::write(output_path, format!("{}\n{}", header, body))
}

/// Split words into chunks of 2-3 words each, preferring 3 when possible.
fn group_words(words: &[&str]) -> Vec<String> {
    if words.is_empty() {
        return vec![];
    }

    let total = words.len();
    if total <= 3 {
        return vec![words.join(" ")];
    }

    let mut chunks = Vec::new();
    let mut i = 0;

    while i < total {
        let remaining = total - i;
        let chunk_size = if remaining >= 5 {
            3
        } else if remaining == 4 {
            2
        } else {
            remaining
        };

        let end = (i + chunk_size).min(total);
        chunks.push(words[i..end].join(" "));
        i = end;
    }

    chunks
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_format_timestamp_ass_zero() {
        assert_eq!(format_timestamp_ass(0.0), "0:00:00.00");
    }

    #[test]
    fn test_format_timestamp_ass_one_hour() {
        assert_eq!(format_timestamp_ass(3661.5), "1:01:01.50");
    }

    #[test]
    fn test_format_timestamp_ass_negative_becomes_zero() {
        assert_eq!(format_timestamp_ass(-5.0), "0:00:00.00");
    }

    #[test]
    fn test_srt_to_ass_basic() {
        let entries = vec![
            (0.0, 2.5, "Hello world".to_string()),
            (3.0, 5.0, "Second line".to_string()),
        ];
        let tmp = std::env::temp_dir().join("test_basic.ass");
        let path = tmp.to_string_lossy();
        srt_to_ass(&entries, &path, "Default").unwrap();

        let content = fs::read_to_string(&tmp).unwrap();
        assert!(content.contains("[Script Info]"));
        assert!(content.contains("[Events]"));
        assert!(content.contains("Dialogue: 0,0:00:00.00, 0:00:02.50, Default,,0,0,0,,Hello world"));
        assert!(content.contains("Dialogue: 0,0:00:03.00, 0:00:05.00, Default,,0,0,0,,Second line"));

        fs::remove_file(&tmp).ok();
    }

    #[test]
    fn test_srt_to_ass_escapes_special_chars() {
        let entries = vec![(0.0, 1.0, "text {with} special \\ chars".to_string())];
        let tmp = std::env::temp_dir().join("test_escape.ass");
        let path = tmp.to_string_lossy();
        srt_to_ass(&entries, &path, "Default").unwrap();

        let content = fs::read_to_string(&tmp).unwrap();
        assert!(content.contains("\\{with\\}"));
        assert!(content.contains("\\\\ chars"));

        fs::remove_file(&tmp).ok();
    }

    #[test]
    fn test_srt_to_ass_custom_style() {
        let entries = vec![(0.0, 1.0, "test".to_string())];
        let tmp = std::env::temp_dir().join("test_style.ass");
        let path = tmp.to_string_lossy();
        srt_to_ass(&entries, &path, "MyStyle").unwrap();

        let content = fs::read_to_string(&tmp).unwrap();
        assert!(content.contains("Style: MyStyle,Bebas Neue,84"));

        fs::remove_file(&tmp).ok();
    }

    #[test]
    fn test_group_words_single_chunk() {
        let words = vec!["hello", "world"];
        let chunks = group_words(&words);
        assert_eq!(chunks, vec!["hello world"]);
    }

    #[test]
    fn test_group_words_six_words() {
        let words = vec!["hello", "world", "this", "is", "a", "test"];
        let chunks = group_words(&words);
        assert_eq!(chunks, vec!["hello world this", "is a test"]);
    }

    #[test]
    fn test_group_words_eight_words() {
        let words = vec![
            "Here", "is", "the", "thing", "most", "people", "don't", "know",
        ];
        let chunks = group_words(&words);
        assert_eq!(
            chunks,
            vec!["Here is the", "thing most people", "don't know"]
        );
    }

    #[test]
    fn test_group_words_empty() {
        let words: Vec<&str> = vec![];
        let chunks = group_words(&words);
        assert!(chunks.is_empty());
    }

    #[test]
    fn test_group_words_single_word() {
        let words = vec!["hello"];
        let chunks = group_words(&words);
        assert_eq!(chunks, vec!["hello"]);
    }

    #[test]
    fn test_group_words_four_words() {
        let words = vec!["one", "two", "three", "four"];
        let chunks = group_words(&words);
        assert_eq!(chunks, vec!["one two", "three four"]);
    }

    #[test]
    fn test_group_words_five_words() {
        let words = vec!["a", "b", "c", "d", "e"];
        let chunks = group_words(&words);
        assert_eq!(chunks, vec!["a b c", "d e"]);
    }

    #[test]
    fn test_generate_kinetic_captions_basic() {
        let entries = vec![(
            0.0,
            3.0,
            "Here is the thing most people don't know".to_string(),
        )];
        let tmp = std::env::temp_dir().join("test_kinetic.ass");
        let path = tmp.to_string_lossy();
        generate_kinetic_captions(&entries, &path, "KineticBold", "&H00D7FF").unwrap();

        let content = fs::read_to_string(&tmp).unwrap();
        assert!(content.contains("[Script Info]"));
        assert!(content.contains("[V4+ Styles]"));
        assert!(content.contains("KineticBold,Bebas Neue,88"));
        assert!(content.contains("KineticDim,Bebas Neue,72"));
        assert!(content.contains("[Events]"));

        fs::remove_file(&tmp).ok();
    }

    #[test]
    fn test_generate_kinetic_captions_timing_split() {
        let entries = vec![(0.0, 3.0, "one two three four five six".to_string())];
        let tmp = std::env::temp_dir().join("test_kinetic_timing.ass");
        let path = tmp.to_string_lossy();
        generate_kinetic_captions(&entries, &path, "KineticBold", "&H00D7FF").unwrap();

        let content = fs::read_to_string(&tmp).unwrap();
        let lines: Vec<&str> = content
            .lines()
            .filter(|l| l.starts_with("Dialogue:"))
            .collect();
        assert_eq!(lines.len(), 2);

        fs::remove_file(&tmp).ok();
    }

    #[test]
    fn test_generate_kinetic_captions_escapes_special_chars() {
        let entries = vec![(0.0, 2.0, "text {with} special \\ chars".to_string())];
        let tmp = std::env::temp_dir().join("test_kinetic_escape.ass");
        let path = tmp.to_string_lossy();
        generate_kinetic_captions(&entries, &path, "KineticBold", "&H00D7FF").unwrap();

        let content = fs::read_to_string(&tmp).unwrap();
        assert!(content.contains("\\{with\\}"));
        assert!(content.contains("\\\\ chars"));

        fs::remove_file(&tmp).ok();
    }

    #[test]
    fn test_generate_kinetic_captions_empty_text() {
        let entries = vec![(0.0, 1.0, "".to_string())];
        let tmp = std::env::temp_dir().join("test_kinetic_empty.ass");
        let path = tmp.to_string_lossy();
        generate_kinetic_captions(&entries, &path, "KineticBold", "&H00D7FF").unwrap();

        let content = fs::read_to_string(&tmp).unwrap();
        let dialogue_count = content
            .lines()
            .filter(|l| l.starts_with("Dialogue:"))
            .count();
        assert_eq!(dialogue_count, 0);

        fs::remove_file(&tmp).ok();
    }

    #[test]
    fn test_generate_kinetic_captions_single_word() {
        let entries = vec![(0.0, 1.0, "Hello".to_string())];
        let tmp = std::env::temp_dir().join("test_kinetic_single.ass");
        let path = tmp.to_string_lossy();
        generate_kinetic_captions(&entries, &path, "KineticBold", "&H00D7FF").unwrap();

        let content = fs::read_to_string(&tmp).unwrap();
        let lines: Vec<&str> = content
            .lines()
            .filter(|l| l.starts_with("Dialogue:"))
            .collect();
        assert_eq!(lines.len(), 1);
        assert!(lines[0].contains("Hello"));

        fs::remove_file(&tmp).ok();
    }

    #[test]
    fn test_generate_kinetic_captions_multiple_entries() {
        let entries = vec![
            (0.0, 2.0, "First caption here".to_string()),
            (3.0, 5.0, "Second caption now".to_string()),
        ];
        let tmp = std::env::temp_dir().join("test_kinetic_multi.ass");
        let path = tmp.to_string_lossy();
        generate_kinetic_captions(&entries, &path, "KineticBold", "&H00D7FF").unwrap();

        let content = fs::read_to_string(&tmp).unwrap();
        let lines: Vec<&str> = content
            .lines()
            .filter(|l| l.starts_with("Dialogue:"))
            .collect();
        assert_eq!(lines.len(), 2);

        fs::remove_file(&tmp).ok();
    }
}
