use std::fs;

/// Convert SRT entries to ASS subtitle format for ffmpeg burn-in.
/// Matches the behavior of the Python ass_from_srt.py script.
pub fn srt_to_ass(
    entries: &[(f64, f64, String)],
    output_path: &str,
    style_name: &str,
) -> Result<(), std::io::Error> {
    let header = r#"[Script Info]
; Script generated by openscript-rs
ScriptType: v4.00+
WrapStyle: 0
PlayResX: 1080
PlayResY: 1920

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: #STYLE#,Bebas Neue,84,&H00FFFFFF,&H000000FF,&H00000000,&H80000000,-1,0,0,0,100,100,0,0,1,3,8,2,108,108,960,1
"#;
    let header = header.replace("#STYLE#", style_name);

    let mut body = String::from(
        "[Events]\nFormat: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text\n",
    );

    for (start, end, text) in entries {
        let start_str = format_timestamp_ass(*start);
        let end_str = format_timestamp_ass(*end);
        let escaped = text
            .replace('\\', "\\\\")
            .replace('{', "\\{")
            .replace('}', "\\}");
        body.push_str(&format!(
            "Dialogue: 0,{}, {}, {},,0,0,0,,{}\n",
            start_str, end_str, style_name, escaped
        ));
    }

    fs::write(output_path, format!("{}\n{}", header, body))
}

fn format_timestamp_ass(seconds: f64) -> String {
    let secs = if seconds < 0.0 { 0.0 } else { seconds };
    let cs = ((secs % 1.0) * 100.0).round() as u32;
    let s_int = secs as u64;
    let hh = s_int / 3600;
    let mm = (s_int % 3600) / 60;
    let ss = s_int % 60;
    format!("{:01}:{:02}:{:02}.{:02}", hh, mm, ss, cs)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_format_timestamp_ass_zero() {
        assert_eq!(format_timestamp_ass(0.0), "0:00:00.00");
    }

    #[test]
    fn test_format_timestamp_ass_one_hour() {
        assert_eq!(format_timestamp_ass(3661.5), "1:01:01.50");
    }

    #[test]
    fn test_format_timestamp_ass_negative_becomes_zero() {
        assert_eq!(format_timestamp_ass(-5.0), "0:00:00.00");
    }

    #[test]
    fn test_srt_to_ass_basic() {
        let entries = vec![
            (0.0, 2.5, "Hello world".to_string()),
            (3.0, 5.0, "Second line".to_string()),
        ];
        let tmp = std::env::temp_dir().join("test_basic.ass");
        let path = tmp.to_string_lossy();
        srt_to_ass(&entries, &path, "Default").unwrap();

        let content = fs::read_to_string(&tmp).unwrap();
        assert!(content.contains("[Script Info]"));
        assert!(content.contains("[Events]"));
        assert!(content.contains("Dialogue: 0,0:00:00.00, 0:00:02.50, Default,,0,0,0,,Hello world"));
        assert!(content.contains("Dialogue: 0,0:00:03.00, 0:00:05.00, Default,,0,0,0,,Second line"));

        fs::remove_file(&tmp).ok();
    }

    #[test]
    fn test_srt_to_ass_escapes_special_chars() {
        let entries = vec![(0.0, 1.0, "text {with} special \\ chars".to_string())];
        let tmp = std::env::temp_dir().join("test_escape.ass");
        let path = tmp.to_string_lossy();
        srt_to_ass(&entries, &path, "Default").unwrap();

        let content = fs::read_to_string(&tmp).unwrap();
        assert!(content.contains("\\{with\\}"));
        assert!(content.contains("\\\\ chars"));

        fs::remove_file(&tmp).ok();
    }

    #[test]
    fn test_srt_to_ass_custom_style() {
        let entries = vec![(0.0, 1.0, "test".to_string())];
        let tmp = std::env::temp_dir().join("test_style.ass");
        let path = tmp.to_string_lossy();
        srt_to_ass(&entries, &path, "MyStyle").unwrap();

        let content = fs::read_to_string(&tmp).unwrap();
        assert!(content.contains("Style: MyStyle,Bebas Neue,84"));

        fs::remove_file(&tmp).ok();
    }
}
